services:

  server:
    container_name: mqtt_framework_server
    build: .
    command: gunicorn -b 0.0.0.0:8000 core.wsgi --log-file -
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt_user:mqtt_password@mosquitto:1883
    volumes:
      - .:/app
    links:
      - mosquitto

  mosquitto:
    container_name: mqtt_framework_mosquitto
    build:
      context: ./.infra/mosquitto/
      args:
        - MQTT_USER=mqtt_user
        - MQTT_PASSWORD=mqtt_password
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./.dev_data/mosquitto/:/mosquitto/data/

  mqttx:
    container_name: mqtt_framework_mqttx
    image: emqx/mqttx-web:latest
    ports:
      - "1884:80"
