services:
  server:
    container_name: mqtt_framework_server
    build: .
    command: python manage.py runmqtt
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt_user:mqtt_password@mosquitto:1883
      - CACHE_URL=memcached://memcached:11211
    volumes:
      - .:/app
    links:
      - mosquitto
      - memcached

  mosquitto:
    container_name: mqtt_framework_mosquitto
    build:
      context: ./.infra/mosquitto/
      args:
        - MQTT_USER=mqtt_user
        - MQTT_PASSWORD=mqtt_password
    volumes:
      - ./.dev_data/mosquitto/:/mosquitto/data/

  memcached:
    container_name: mqtt_framework_memcached
    image: memcached:1.6-alpine
