name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Python Packages Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          save-always: true
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt', 'setup.py') }}

      - name: Install dependencies
        run: pip install --upgrade twine build

      - name: Build and upload package to PyPI
        run: |
          python -m build --sdist --wheel .
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
