name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Test With Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    env:
      # See docker-compose.yml
      MQTT_BROKER_URL: mqtt://mqtt_user:mqtt_password@localhost:1883
      CACHE_URL: memcached://localhost:11211

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install `libmemcached-dev`
        if: ${{ matrix.python-version == '3.12' }}
        run: sudo apt-get install libmemcached-dev zlib1g-dev

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools virtualenv wheel
          pip install --upgrade coverage tox

      - name: Get auxiliary services up
        run: docker compose -f docker-compose.yml -f docker-compose-ci.yml up -d mosquitto memcached

      - name: Run tox targets for ${{ matrix.python-version }}
        run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
