name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Testing Python=${{ matrix.python-version }}/Django=${{ matrix.django-version }}/DRF=${{ matrix.drf-version }}/Pydantic=${{ matrix.pydantic-version }}
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: --health-cmd="echo stats | nc -q1 localhost 11211 | grep -q 'version\|uptime'"

      mosquitto:
        image: custom_mosquitto:.infra/mosquitto/Dockerfile
        ports:
          - 1883:1883

    strategy:
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        django-version:
          - '3.2'
          - '4.2'
          - '5.0'
        drf-version:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.15'
        pydantic-version:
          - '2.7'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install coverage codecov-cli django-cache-url>=3.4.5 django==${{ matrix.django-version }} djangorestframework==${{ matrix.drf-version }} pydantic==${{ matrix.pydantic-version }}

      - name: Run tests
        run: coverage run manage.py test

      - name: Upload coverage
        run: codecov
