name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Testing Python=${{ matrix.python-version }}/Django=${{ matrix.django-version }}/DRF=${{ matrix.drf-version }}/Pydantic=${{ matrix.pydantic-version }}
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: --health-cmd="echo stats | nc -q1 localhost 11211 | grep -q 'version\|uptime'"

      mosquitto:
        image: .infra/mosquitto/Dockerfile  # This is not working
        ports:
          - 1883:1883

    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools virtualenv wheel
          pip install --upgrade coverage codecov-cli tox

      - name: Run tox targets for ${{ matrix.python-version }}
        run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)

      - name: Upload coverage
        run: codecov
